### PR TITLE
Add invalidateblock RPC call

### PR DESCRIPTION
**Pull request by galt-tr**

### CODE REVIEW

**Comment by mrz1836** [comment]
@jadwahab can we re-open this please?

**Comment by jadwahab** [comment]
@mrz1836 yupp, don't remember what exactly was going on here and what's causing the issues. What do you need this for?

**Comment by galt-tr** [comment]
@jadwahab I want to be able to call `invalidateblock` RPC call with this lib. No issues really, the linter github action is just broken. Looking for someone to review/merge so I don't need to carry a fork any longer. Thanks!

EDIT: Oh sorry, I didn't even notice the failing tests. Updating...

**Comment by jadwahab** [comment]
yupp seems like the build pipeline is also failing

**Pull request closed without merging**
